package eramo.resultgate.domain.model.products.orders

import android.os.Parcelable
import eramo.resultgate.util.state.UiText
import kotlinx.parcelize.Parcelize
import kotlinx.parcelize.RawValue

@Parcelize
data class OrderModel(
    var orderId: String,
    var orderRkm: String,
    var orderFrom: String,
    var orderDate: String,
    var orderDateAr: String,
    var orderTime: String,
    var orderDateS: String,
    var payTypeId: String,
    var payType: @RawValue UiText,
    var clientIdFk: String,
    var commission: String,
    var getWayPercent: String,
    var allSum: String,
    var allSumInstall: String,
    var allSumExtras: String,
    var promoCode: @RawValue UiText,
    var promoCodePercent: String,
    var customerId: String,
    var customerName: String,
    var customerMob: String,
    var customerAddress: String,
    var customAddress: String,
    var vendorIdFk: String,
    var status: @RawValue UiText,
    var created: String,
    var updated: String,
    var actionInProgressDate: String,
    var actionInProgressTime: String,
    var actionInProgressUser: String,
    var actionCompletedDate: String,
    var actionCompletedTime: String,
    var actionCompletedUser: String,
    var actionCancelledDate: String,
    var actionCancelledTime: String,
    var actionCancelledUser: String,
    var actionCancelledFrom: String,
    var token: String,
    var deliveryDate: String,
    var installationDate: String,
    var technicalIdFk: String,
    var driverIdFk: String,
    var comments: String,
    var commentsLastUser: String,
    var commentsLastUpdatedDate: String,
    var orderDetails: List<OrderDetailsModel>,
    var orderProductExtraModels: List<AllProductExtrasModel>,
    var allDiscountsFeesModels: List<DiscountFeesModel>,
    var sumExtraFees: Int,
    var sumDiscountsFees: Int,
    var totalShipping: Double,
    var totalTaxes: Double,
    var finalTotal: Double
) : Parcelable